spring:
  application:
    name: FizioApp
  security:
    oauth2:
      jwks-url: ${JWKS_URL}
      roles-path: resource_access/fizio-test/roles
      username-claim: preferred_username
      name-claim: name
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}


server:
  port: 8081
  max-http-header-size: 65536
  servlet:
    context-path: /
  tomcat:
    accept-count: 32

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
