version: '3.9'

services:
  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  monitoring:
    build:
      context: ./monitoring-dashboard
      dockerfile: Dockerfile
    ports:
      - "50000:5000"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - "KEYCLOAK_IMPORT= /opt/keycloak/data/import/realm-export.json"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    volumes:
      - ./keycloak-db/:/opt/keycloak/data/import/:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --http-port=8080 --import-realm'

  server:
    depends_on:
      - "db"
      - "keycloak"
    build:
      context: ./fizio-app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always

volumes:
  mysql-volume:
