version: '3.9'

services:
  db:
    build:
      context: ./sql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

  monitoring:
    build:
      context: ./monitoring-dashboard
      dockerfile: Dockerfile
    ports:
      - "50000:5000"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - "KEYCLOAK_IMPORT= /opt/keycloak/data/imports/realm-export.json"
      - "KEYCLOAK_ADMIN=admin"
      - "KEYCLOAK_ADMIN_PASSWORD=admin"
    volumes:
      - ./keycloak-db/:/opt/keycloak/data/imports/:ro
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --http-port=8080 --import-realm'

  server:
    depends_on:
      - keycloak
      - db
    build:
      context: ./fizio-app
      dockerfile: Dockerfile
    environment:
      - "SERVER_PORT=8081"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fizio"
      - "SPRING_DATASOURCE_USERNAME=fizioUser"
      - "SPRING_DATASOURCE_PASSWORD=fizioUser"
    ports:
      - "8081:8081"

volumes:
  mysql-volume:
