apiVersion: v1
kind: Service
metadata:
  name: serverService
spec:
  selector:
    app: server
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  - protocol: "TCP"
    port: 8081
    targetPort: 8081
  type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:latest
        imagePullPolicy: Always
        volumeMounts:
          - name: logs
            mountPath: /usr/app/tpo/logs
        ports:
        - containerPort: 8080
          name: serverPort
        - containerPort: 8081
          name: swaggerPort


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serverIngress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: serverService
            port:
              number: 8080
      - path: /swagger-ui/index.html#/
        pathType: Prefix
        backend:
          service:
            name: serverService
            port:
              number: 8081
