apiVersion: v1
kind: Service
metadata:
  name: keycloakService
spec:
  selector:
    app: keycloak
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer


apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloakIngress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloakService
            port:
              number: 8080
